SELECT 'customer', CUSTOMER.id, CUSTOMER.customer_name
FROM 
    CUSTOMER LEFT JOIN INVOICE ON CUSTOMER.id = INVOICE.CUSTOMER_ID
WHERE
    INVOICE.INVOICE_NUMBER IS NULL
UNION 
SELECT 'product', PRODUCT.id, PRODUCT.product_name
FROM PRODUCT LEFT JOIN INVOICE_ITEM ON PRODUCT.ID = INVOICE_ITEM.PRODUCT_ID
WHERE INVOICE_ID IS NULL
